version: "3.6"
services:
  jenkins:
    image: archilab-jenkins
    env_file:
      - ./env.list
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - archilab-jenkins-data:/var/jenkins_home
    user: root
    secrets:
      - GITHUB_TOKEN
      - GITHUB_USERNAME
      - GITHUB_PASSWORD
      - NEXUS_USERNAME
      - NEXUS_PASSWORD
      - PROX_PROD_CERTS_SECRET
      - PROX_PROD_CERTS_CLIENT
      - PROX_PROD_CERTS_CA_SERVER
      - PROX_DEV_CERTS_SECRET
      - PROX_DEV_CERTS_CLIENT
      - PROX_DEV_CERTS_CA_SERVER
      - PROX_GP_WS2019_CERTS_SECRET
      - PROX_GP_WS2019_CERTS_CLIENT
      - PROX_GP_WS2019_CERTS_CA_SERVER
      - COALBASE_PROD_CERTS_SECRET
      - COALBASE_PROD_CERTS_CLIENT
      - COALBASE_PROD_CERTS_CA_SERVER
      - COALBASE_DEV_CERTS_SECRET
      - COALBASE_DEV_CERTS_CLIENT
      - COALBASE_DEV_CERTS_CA_SERVER

secrets:
  GITHUB_TOKEN:
    external: true
  GITHUB_USERNAME:
    external: true
  GITHUB_PASSWORD:
    external: true
  NEXUS_USERNAME:
    external: true
  NEXUS_PASSWORD:
    external: true
  PROX_PROD_CERTS_SECRET:
    external: true
  PROX_PROD_CERTS_CLIENT:
    external: true
  PROX_PROD_CERTS_CA_SERVER:
    external: true
  PROX_DEV_CERTS_SECRET:
    external: true
  PROX_DEV_CERTS_CLIENT:
    external: true
  PROX_DEV_CERTS_CA_SERVER:
    external: true
  PROX_GP_WS2019_CERTS_SECRET:
    external: true
  PROX_GP_WS2019_CERTS_CLIENT:
    external: true
  PROX_GP_WS2019_CERTS_CA_SERVER:
    external: true
  COALBASE_PROD_CERTS_SECRET:
    external: true
  COALBASE_PROD_CERTS_CLIENT:
    external: true
  COALBASE_PROD_CERTS_CA_SERVER:
    external: true
  COALBASE_DEV_CERTS_SECRET:
    external: true
  COALBASE_DEV_CERTS_CLIENT:
    external: true
  COALBASE_DEV_CERTS_CA_SERVER:
    external: true

volumes:
  archilab-jenkins-data:
