version: "3.6"
services:
  jenkins:
    image: archilab-jenkins
    env_file:
      - ./env.list
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    secrets:
      - jcasc_vault

secrets:
  jcasc_vault:
    file: ./secrets/jcasc_vault
