jobs:
  - file: /var/jenkins_home/jobdsl/prox-service-discovery.groovy
  - file: /var/jenkins_home/jobdsl/prox-api-gateway.groovy
  - file: /var/jenkins_home/jobdsl/prox-project-service.groovy
  - file: /var/jenkins_home/jobdsl/prox-tag-service.groovy
  - file: /var/jenkins_home/jobdsl/prox-web-client.groovy
  - file: /var/jenkins_home/jobdsl/prox-professor-profile-service.groovy
  - file: /var/jenkins_home/jobdsl/prox-company-profile-service.groovy
  - file: /var/jenkins_home/jobdsl/prox-job-service.groovy
  - file: /var/jenkins_home/jobdsl/list-views.groovy
