jobs:
  - script: >
      pipelineJob('prox-project-service') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-project-service')
                          credentials('archilab-github-jenkins')
                      }
                      branches('jenkins-migration')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-module-service') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-module-service')
                          credentials('archilab-github-jenkins')
                      }
                      branches('jenkins-migration')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-web-client') {
        definition {
          cpsScm {
              scriptPath 'src/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-web-client')
                          credentials('archilab-github-jenkins')
                      }
                      branches('jenkins-migration')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-service-discovery') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-service-discovery')
                          credentials('archilab-github-jenkins')
                      }
                      branches('jenkins-migration')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-api-gateway') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-api-gateway')
                          credentials('archilab-github-jenkins')
                      }
                      branches('jenkins-migration')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }