jobs:
  # - file: /var/jenkins_home/jobdsl/coalbase-message-broker.groovy
  # - file: /var/jenkins_home/jobdsl/coalbase-service-discovery.groovy
  # - file: /var/jenkins_home/jobdsl/coalbase-api-gateway.groovy
  # - file: /var/jenkins_home/jobdsl/coalbase-learning-outcome.groovy
  # - file: /var/jenkins_home/jobdsl/coalbase-resource.groovy
  # - file: /var/jenkins_home/jobdsl/coalbase-comment.groovy
  # - file: /var/jenkins_home/jobdsl/coalbase-frontend.groovy

  - file: /var/jenkins_home/jobdsl/fae-message-broker.groovy
  - file: /var/jenkins_home/jobdsl/fae-service-discovery.groovy
  - file: /var/jenkins_home/jobdsl/fae-api-gateway.groovy
  - file: /var/jenkins_home/jobdsl/fae-node-red.groovy
  - file: /var/jenkins_home/jobdsl/fae-shop-demo.groovy
  - file: /var/jenkins_home/jobdsl/fae-draussen-ortung.groovy
  - file: /var/jenkins_home/jobdsl/fae-team-1-service.groovy
  - file: /var/jenkins_home/jobdsl/fae-team-2-service.groovy
  - file: /var/jenkins_home/jobdsl/fae-team-3-service.groovy
  - file: /var/jenkins_home/jobdsl/fae-team-4-service.groovy
  - file: /var/jenkins_home/jobdsl/fae-documentation-server.groovy

  - file: /var/jenkins_home/jobdsl/prox-service-discovery.groovy
  - file: /var/jenkins_home/jobdsl/prox-api-gateway.groovy
  - file: /var/jenkins_home/jobdsl/prox-project-service.groovy
  - file: /var/jenkins_home/jobdsl/prox-tag-service.groovy
  - file: /var/jenkins_home/jobdsl/prox-web-client.groovy
  - file: /var/jenkins_home/jobdsl/prox-service-discovery-dev.groovy
  - file: /var/jenkins_home/jobdsl/prox-api-gateway-dev.groovy
  - file: /var/jenkins_home/jobdsl/prox-project-service-dev.groovy
  - file: /var/jenkins_home/jobdsl/prox-tag-service-dev.groovy
  - file: /var/jenkins_home/jobdsl/prox-web-client-dev.groovy
  - file: /var/jenkins_home/jobdsl/prox-professor-profile-service.groovy

  - file: /var/jenkins_home/jobdsl/list-views.groovy
