jobs:
  - file: /var/jenkins_home/jobdsl/prox-project-service.groovy
  - file: /var/jenkins_home/jobdsl/prox-module-service.groovy
  - file: /var/jenkins_home/jobdsl/prox-web-client.groovy
  - file: /var/jenkins_home/jobdsl/prox-service-discovery.groovy
  - file: /var/jenkins_home/jobdsl/prox-api-gateway.groovy
  - file: /var/jenkins_home/jobdsl/prox-tag-service.groovy
  - file: /var/jenkins_home/jobdsl/prox-search-service.groovy
  - file: /var/jenkins_home/jobdsl/prox-proposal-service.groovy
  - file: /var/jenkins_home/jobdsl/prox-project-service-dev.groovy
  - file: /var/jenkins_home/jobdsl/prox-module-service-dev.groovy
  - file: /var/jenkins_home/jobdsl/prox-web-client-dev.groovy
  - file: /var/jenkins_home/jobdsl/prox-service-discovery-dev.groovy
  - file: /var/jenkins_home/jobdsl/prox-api-gateway-dev.groovy
  - file: /var/jenkins_home/jobdsl/prox-tag-service-dev.groovy
  - file: /var/jenkins_home/jobdsl/prox-search-service-dev.groovy
  - file: /var/jenkins_home/jobdsl/prox-proposal-service-dev.groovy
  - file: /var/jenkins_home/jobdsl/prox-project-service-gp-ws2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-module-service-gp-ws2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-web-client-gp-ws2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-service-discovery-gp-ws2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-api-gateway-gp-ws2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-tag-service-gp-ws2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-search-service-gp-ws2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-project-service-pp-ss2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-module-service-pp-ss2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-web-client-pp-ss2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-service-discovery-pp-ss2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-api-gateway-pp-ss2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-proposal-service-pp-ss2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-project-service-ip-ws2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-module-service-ip-ws2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-web-client-ip-ws2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-service-discovery-ip-ws2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-api-gateway-ip-ws2019.groovy
  - file: /var/jenkins_home/jobdsl/prox-user-profile-service-ip-ws2019.groovy
  - file: /var/jenkins_home/jobdsl/coalbase-api-gateway.groovy
  - file: /var/jenkins_home/jobdsl/coalbase-comment.groovy
  - file: /var/jenkins_home/jobdsl/coalbase-frontend.groovy
  - file: /var/jenkins_home/jobdsl/coalbase-learning-outcome.groovy
  - file: /var/jenkins_home/jobdsl/coalbase-message-broker.groovy
  - file: /var/jenkins_home/jobdsl/coalbase-resource.groovy
  - file: /var/jenkins_home/jobdsl/coalbase-service-discovery.groovy
  - file: /var/jenkins_home/jobdsl/fae-api-gateway.groovy
  - file: /var/jenkins_home/jobdsl/fae-message-broker.groovy
  - file: /var/jenkins_home/jobdsl/fae-service-discovery.groovy
  - file: /var/jenkins_home/jobdsl/fae-shop-demo.groovy
  - file: /var/jenkins_home/jobdsl/fae-team-1-service.groovy
  - file: /var/jenkins_home/jobdsl/fae-team-2-service.groovy
  - file: /var/jenkins_home/jobdsl/fae-team-3-service.groovy
  - file: /var/jenkins_home/jobdsl/fae-team-4-service.groovy
  - file: /var/jenkins_home/jobdsl/fae-documentation-server.groovy
