jobs:
  - script: >
      pipelineJob('prox-project-service') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-project-service')
                          credentials('archilab-github-jenkins')
                      }
                      branches('master')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-module-service') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-module-service')
                          credentials('archilab-github-jenkins')
                      }
                      branches('master')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-web-client') {
        definition {
          cpsScm {
              scriptPath 'src/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-web-client')
                          credentials('archilab-github-jenkins')
                      }
                      branches('master')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-service-discovery') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-service-discovery')
                          credentials('archilab-github-jenkins')
                      }
                      branches('master')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-api-gateway') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-api-gateway')
                          credentials('archilab-github-jenkins')
                      }
                      branches('master')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }
  - script: >
      pipelineJob('prox-project-service-dev') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-project-service')
                          credentials('archilab-github-jenkins')
                      }
                      branches('dev')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-module-service-dev') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-module-service')
                          credentials('archilab-github-jenkins')
                      }
                      branches('dev')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-web-client-dev') {
        definition {
          cpsScm {
              scriptPath 'src/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-web-client')
                          credentials('archilab-github-jenkins')
                      }
                      branches('dev')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-service-discovery-dev') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-service-discovery')
                          credentials('archilab-github-jenkins')
                      }
                      branches('dev')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-api-gateway-dev') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-api-gateway')
                          credentials('archilab-github-jenkins')
                      }
                      branches('dev')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-project-service-gp-ws2019') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-project-service')
                          credentials('archilab-github-jenkins')
                      }
                      branches('gp-ws2019')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-module-service-gp-ws2019') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-module-service')
                          credentials('archilab-github-jenkins')
                      }
                      branches('gp-ws2019')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-web-client-gp-ws2019') {
        definition {
          cpsScm {
              scriptPath 'src/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-web-client')
                          credentials('archilab-github-jenkins')
                      }
                      branches('gp-ws2019')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-service-discovery-gp-ws2019') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-service-discovery')
                          credentials('archilab-github-jenkins')
                      }
                      branches('gp-ws2019')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('prox-api-gateway-gp-ws2019') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/prox-api-gateway')
                          credentials('archilab-github-jenkins')
                      }
                      branches('gp-ws2019')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('coalbase-api-gateway') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/coalbase-api-gateway')
                          credentials('archilab-github-jenkins')
                      }
                      branches('jenkins-migration')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('coalbase-comment') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/coalbase-comment')
                          credentials('archilab-github-jenkins')
                      }
                      branches('jenkins-migration')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('coalbase-frontend') {
        definition {
          cpsScm {
              scriptPath 'Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/coalbase-frontend')
                          credentials('archilab-github-jenkins')
                      }
                      branches('jenkins-migration')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('coalbase-infrastructure') {
        definition {
          cpsScm {
              scriptPath 'Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/coalbase-infrastructure')
                          credentials('archilab-github-jenkins')
                      }
                      branches('jenkins-migration')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('coalbase-keycloak') {
        definition {
          cpsScm {
              scriptPath 'Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/coalbase-keycloak')
                          credentials('archilab-github-jenkins')
                      }
                      branches('jenkins-migration')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('coalbase-learning-outcome') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/coalbase-learning-outcome')
                          credentials('archilab-github-jenkins')
                      }
                      branches('jenkins-migration')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('coalbase-message-broker') {
        definition {
          cpsScm {
              scriptPath 'Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/coalbase-message-broker')
                          credentials('archilab-github-jenkins')
                      }
                      branches('jenkins-migration')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('coalbase-resource') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/coalbase-resource')
                          credentials('archilab-github-jenkins')
                      }
                      branches('jenkins-migration')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }

  - script: >
      pipelineJob('coalbase-service-discovery') {
        definition {
          cpsScm {
              scriptPath 'src/main/jenkins/Jenkinsfile'
              scm {
                  git {
                      remote {
                          github('Archi-Lab/coalbase-service-discovery')
                          credentials('archilab-github-jenkins')
                      }
                      branches('jenkins-migration')
                  }
              }
              lightweight(true)
          }
        }
        triggers {
            githubPush()
        }
      }
